# Generated by Django 3.0.6 on 2020-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='hamspamtweets_user',
            field=models.FileField(blank=True, upload_to='classify/files'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='spammywordsusers_user',
            field=models.FileField(blank=True, upload_to='classify/files'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='spamurl_user',
            field=models.FileField(blank=True, upload_to='classify/files'),
        ),
    ]
