# Generated by Django 3.0.6 on 2020-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HamSpamTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('label', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SpamURLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spammy_words', models.CharField(max_length=256)),
                ('spammy_users', models.CharField(max_length=256)),
            ],
        ),
    ]
